### ISSUE TITLE
Able send messages

### ISSUE THREAD

**Issue by estefaniaguardado** [EstefaniaGuardado/Chatte#8]
Able send messages of user to contacts through the view of chat

**Comment by EstefaniaGuardado** [comment]
Resources:

- https://github.com/slackhq/SlackTextViewController

- https://github.com/lukaskubanek/LoremIpsum

**Comment by estefaniaguardado** [comment]
Resolve in pull request: https://github.com/EstefaniaGuardado/exampleXmpp/pull/23
